### ISSUE TITLE
Assess quality of unit tests

### ISSUE THREAD

**Issue by mthmulders** [bmarwell/twitter-metricbot#103]
It would be cool to see the quality of the unit tests. We can do that by injecting mutations in the production code and running the tests again to see if they detect the mutations.

This process is called "mutation testing". For Java, we can use [PIT](https://pitest.org/). It can generate a static HTML file as output, or alternatively, we could upload the report to the [Stryker Dashboard](https://dashboard.stryker-mutator.io/). It will give a nice report and in addition, provide an extra badge for the [**README**](https://github.com/bmarwell/twitter-metricbot/blob/main/README.adoc).

**Comment by mthmulders** [comment]
@bmarwell Which report(s) would you prefer?

1. Default HTML report - can only be viewed on the machine where it was generated
2. Enhanced HTML report - can only be viewed on the machine where it was generated
3. Online dashboard - can only be viewed on the Stryker dashboard, but not locally

I could imagine you'd want a report that you can inspect locally, but for GitHub Actions, you'd want the Enhanced HTML report?

**Comment by bmarwell** [comment]
Huh. Whatever suits you best. I have no experience here, and thus no preference.
Locally would be sufficient for now. It's a small project, and we can create issues from local reports as needed.
