### ISSUE TITLE
Set up code coverage and badge

### ISSUE THREAD

**Issue by bmarwell** [bmarwell/twitter-metricbot#93]

**Comment by mthmulders** [comment]
How about mutation testing (with a nice badge and dashboard, of course). I could help you set up if you like, or maybe you prefer a different issue for that?

**Comment by bmarwell** [comment]
Yes, I would love to add PiTtest or such! :) 
A different issue would be highly appreciated, I am almost done with the coverage now anyway.

**Comment by mthmulders** [comment]
Opened #103 to track this.
